Feature 11 events page backend yevchuk
Social-projects-Rivne/Lunch_Time pull request #11
Opened 2020-03-08 18:38 UTC by yevchuk

2020-03-08 20:27 UTC, vitaliimak requested changes
Great work! But there are some issues.
Also what do you think if we disable all checkstyle rules which connected to imports? I mean 
```
<module name="AvoidStarImport"/>
<module name="CustomImportOrder">
      <property name="sortImportsInGroupAlphabetically" value="true"/>
      <property name="separateLineBetweenGroups" value="true"/>
      <property name="customImportOrderRules" value="STATIC###THIRD_PARTY_PACKAGE"/>
      <property name="tokens" value="IMPORT, STATIC_IMPORT, PACKAGE_DEF"/>
</module>
```
They are really annoying

2020-03-08 20:27 UTC, vitaliimak commented on server/src/main/java/com/lunchtime/controllers/EventController.java
> +@RequestMapping("/events")
Should we add "/api" prefix in every endpoints? As it is common practice in REST services (e.g. github, google, etc)

2020-03-08 20:27 UTC, vitaliimak commented on server/src/main/java/com/lunchtime/controllers/EventController.java
> +        return new ResponseEntity<>("Event added successfully", HttpStatus.OK);
POST method should  return created entity, it helps frontend developer to understand that server created entity correctly. Also response status code should be 201 - CREATED.

2020-03-08 20:27 UTC, vitaliimak commented on server/src/main/java/com/lunchtime/controllers/EventController.java
> +    public ResponseEntity<?> addOrUpdateEvent(@RequestBody Event event) {
![image](https://user-images.githubusercontent.com/6152066/76169732-da578400-6183-11ea-874d-652bc8a38bf2.png)

You should add minimal validation and return Bed Request if user send stupid data. 
Don't believe user!

2020-03-08 20:27 UTC, vitaliimak commented on server/src/main/java/com/lunchtime/controllers/EventController.java
> +    public void deleteEvent(@RequestParam("id") long id) {
You should use `@DeleteMapping("{id}")` as it is simpler and https://www.restapitutorial.com/lessons/httpmethods.html

2020-03-08 20:27 UTC, vitaliimak commented on server/src/main/java/com/lunchtime/controllers/EventController.java
> +package com.lunchtime.controllers;
There aren't methods `getOneById(id) and update(id)`

2020-03-08 20:27 UTC, vitaliimak commented on server/src/main/java/com/lunchtime/controllers/EventController.java
> +    public ResponseEntity<?> getByCategory(@PathVariable("category") String category) {
For now it isn't so important. But as you implemented this method, I think you should use enum instead of String. Because in current implementation user can sent any request e.g. `GET localhost:8080/events/date` and spring app makes useless request to database

2020-03-08 20:27 UTC, vitalii-mak commented on server/src/main/java/com/lunchtime/entity/Event.java
> +@Getter
Incredible! Thanks for this magic!

2020-03-08 20:27 UTC, vitalii-mak commented on server/src/main/java/com/lunchtime/entity/Event.java
> +    }
I did similar class, and code works without empty constructor. Is it really need? As Java class has empty constructor by default.

2020-03-08 20:27 UTC, vitalii-mak commented on server/src/main/java/com/lunchtime/service/EventServiceImpl.java
> +        eventRepository.deleteById(id);
If user send wrong id (e.g. 999999999999) server throw Error 500. It's cannot be allowed!

2020-03-08 20:27 UTC, vitalii-mak commented on server/src/main/java/com/lunchtime/LunchTimeApplication.java
> +      https://www.tutorialspoint.com/spring_boot/spring_boot_cors_support.htm */
You don't need this comment. Your code speaks for himself.
https://gist.github.com/wojteklu/73c6914cc446146b8b533c0988cf8d29#comments-rules

2020-03-09 07:52 UTC, vitalii-mak commented on server/src/main/java/com/lunchtime/controllers/EventController.java
> +    @GetMapping("date/{startDate}/{endDate}")
You can use more readable format in this case `/date?from=date&to=date`

2020-03-09 08:08 UTC, VanderbiGit commented
round off  back and front in one pull request

2020-03-09 08:55 UTC, vitalii-mak commented on server/src/main/java/com/lunchtime/entity/Event.java
> +    private String eventName;
You don't need use prefix event in naming as it is Event entity

2020-03-09 15:41 UTC, closed without merging