Feature 2 andriy melnyk
Social-projects-Rivne/Lunch_Time pull request #21
Opened 2020-03-16 10:09 UTC by Melnyk9506

Guys oleace check

2020-03-16 15:08 UTC, vitaliimak requested changes
It isn't possible to create new User entity in system without POST method

2020-03-16 15:08 UTC, vitalii-mak commented on server/src/main/java/com/lunchtime/models/Users.java
> +public class Users extends BaseEntity {
You should use singular noun in class name
https://google.github.io/styleguide/javaguide.html#s5.2.2-class-names

2020-03-16 15:08 UTC, vitalii-mak commented on server/src/main/java/com/lunchtime/models/Users.java
> +@Table(name = "users")
You should use singular noun in table name
https://rv-054java.slack.com/archives/CUKLK9279/p1583759766037900

2020-03-16 15:08 UTC, vitalii-mak commented on server/src/main/java/com/lunchtime/controllers/UserController.java
> +//    @PostMapping("/sign-up")
You should avoid useless comments in dev branch

2020-03-16 15:08 UTC, vitalii-mak commented on server/src/main/java/com/lunchtime/controllers/UserController.java
> +    @GetMapping("/all")
You don't need to use ending 'all/ in get method. You can use standard REST approach

2020-03-16 18:36 UTC, vitalii-mak commented
I can't run this code
```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-03-16 20:32:58.320 ERROR 8803 --- [  restartedMain] o.s.b.d.LoggingFailureAnalysisReporter   :

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 1 of constructor in com.lunchtime.controllers.UserController required a bean of type 'org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder' that could not be found.


Action:

Consider defining a bean of type 'org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder' in your configuration.
```

2020-03-18 10:19 UTC, Andrii35 commented on server/src/main/java/com/lunchtime/models/BaseEntity.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
You should change IDENTITY to AUTO, becouse IDENTITY will be used with MySQL

2020-03-18 10:21 UTC, Andrii35 commented on server/src/main/java/com/lunchtime/models/Role.java
> +
Should it not be here a primery key?

2020-03-18 10:26 UTC, Andrii35 reviewed
I run the project with docker. But by testing with Postman i became:
Could not get any response
There was an error connecting to http://localhost:8080/api/users/all.
Why this might have happened:
The server couldn't send a response:


Ensure that the backend is working properly

2020-03-19 12:10 UTC, closed without merging