Feature 2 andriy melnyk
Social-projects-Rivne/Lunch_Time pull request #26
Opened 2020-03-20 10:39 UTC by Melnyk9506

guys pleace chack the code

2020-03-20 11:47 UTC, narekacy commented on server/src/main/java/com/lunchtime/controllers/TokenController.java
> +
It is a good practice to make constructor fields `final`.

2020-03-20 14:12 UTC, VanderbiGit commented
***************************
APPLICATION FAILED TO START
***************************
Description:
Parameter 1 of constructor in com.lunchtime.controllers.UserController required a bean of type 'org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder' that could not be found.
Action:
Consider defining a bean of type 'org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder' in your configuration.
Process finished with exit code 0

Have  you this error?
I can not start project.

2020-03-20 14:14 UTC, VanderbiGit commented
You have Checkstyle error.
Checkstyle found 10 item(s) in 3 file(s)
UserController.java : 3 item(s)
Member name 'bCryptPasswordEncoder' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9]*$'. (16:35) [MemberName]
Parameter name 'bCryptPasswordEncoder' must match pattern '^[a-z]([a-z0-9][a-zA-Z0-9]*)?$'. (19:49) [ParameterName]
Comment has incorrect indentation level 0, expected is 4, indentation should be the same level as line 24. (32:0) [CommentsIndentation]
UserRepository.java : 2 item(s)
GenericWhitespace '>' should followed by whitespace. (7:66) [GenericWhitespace]
WhitespaceAround: '{' is not preceded with whitespace. (7:67) [WhitespaceAround]
Users.java : 5 item(s)
'import' should be separated from previous statement. (2:0) [EmptyLineSeparator]
Abbreviation in name 'photoURL' must contain no more than '2' consecutive capital letters. (30:20) [AbbreviationAsWordInName]
WhitespaceAround: '=' is not followed by whitespace. Empty blocks may only be represented as {} when not part of a multi-block statement (4.1.3) (37:41) [WhitespaceAround]
WhitespaceAround: '=' is not followed by whitespace. Empty blocks may only be represented as {} when not part of a multi-block statement (4.1.3) (38:47) [WhitespaceAround]
WhitespaceAround: '=' is not preceded with whitespace. (38:47) [WhitespaceAround]

2020-03-20 17:09 UTC, vitaliimak requested changes

2020-03-20 17:09 UTC, vitaliimak commented on server/src/main/java/com/lunchtime/controllers/TokenController.java
> +    public String generate(@RequestBody final Person person) {
This method invoke in login page. In this case object Person doesn't exist. You should use object with `username and password` properties

2020-03-20 17:09 UTC, vitaliimak commented on server/src/main/java/com/lunchtime/controllers/TokenController.java
> +public class TokenController {
I think better name will be AuthController. And endpoint must start with `/api` - `/api/auth` or `/api/authenticate`

2020-03-20 17:09 UTC, vitaliimak commented on server/src/main/java/com/lunchtime/models/Person.java
> +@Data
Nice!

2020-03-20 17:09 UTC, vitaliimak commented on server/src/main/java/com/lunchtime/models/Person.java
> +    private String photoUrl;
If you change property name you shouldn't forget to update client part where this property is used

2020-03-20 17:09 UTC, vitaliimak commented on server/src/main/java/com/lunchtime/models/Status.java
> +    ACTIVE, NOT_ACTIVE, DELETED
We have separate property isDeleted. If you decided to change current behavior with `isDeleted` you should remove `isDeleted` property and setters, getters.
Or you can remove `DELETED` field from this enum and left current behavior

2020-03-21 07:19 UTC, vitalii-mak commented
@Melnyk9506 Don't forget to assign PR to yourslf

2020-03-21 15:02 UTC, Andrii35 commented on server/src/main/java/com/lunchtime/models/Role.java
> +
Should't be advised in this entity relationship to entity Person to?

2020-03-21 21:48 UTC, narekacy commented on server/src/main/java/com/lunchtime/models/Person.java
> +    private String photoUrl;
Question to line 32: Do we need phone number to store in `Integer `or `String`?

2020-03-27 13:10 UTC, closed without merging