Feature 79 restaurant list voznyarskyy
Social-projects-Rivne/Lunch_Time pull request #27
Opened 2020-03-23 15:43 UTC by VozNick

2020-03-23 19:16 UTC, vitaliimak requested changes

2020-03-23 19:16 UTC, vitaliimak commented on server/src/main/java/com/lunchtime/models/RestaurantVisit.java
> +package com.lunchtime.models;
Why you create this model? We have restaurant model. A lot of users (persons) use our application, will you plane to create separate RestaurantVisit entity for every user?
Is your task need this functionality?

2020-03-23 19:16 UTC, vitaliimak commented on server/src/main/java/com/lunchtime/implementation/RestaurantServiceImplement.java
> +        return null;
If this code is useless you shouldn't merge it in dev branch

2020-03-23 19:16 UTC, vitalii-mak commented on client/src/components/info/restaurants.js
> +const city = ['Вінницька область', 'Волинська область', 'Дніпропетровська область', 'Донецька область',
Don't use non Latin letters in code. If you need localization, use special tools for it

2020-03-24 09:20 UTC, VozNick commented on server/src/main/java/com/lunchtime/models/RestaurantVisit.java
> +package com.lunchtime.models;
I mean it`s for sorting reason...
in restaurant list page, you can sort restaurants by your last visit. This class will keep dates of all rest. that you have visited...

2020-03-24 09:29 UTC, vitalii-mak commented on server/src/main/java/com/lunchtime/models/RestaurantVisit.java
> +package com.lunchtime.models;
Many users use this app.
Bob visited Restaurant A in 2020-03-05
Maria visited Restaurant A in 2020-03-06
Bob visited Restaurant B in 2020-03-06
...

Your model doesn't connect to Persons, how you prevent collisions between Persons? How you save date 2020-03-05 (Bob) and 2020-03-06 (Maria)? Does this functionality need?

2020-03-25 19:02 UTC, closed without merging