Fix hover button style
Social-projects-Rivne/Lunch_Time pull request #72
Opened 2020-04-23 12:10 UTC by r-yevchuk

2020-04-23 16:30 UTC, vitaliimak requested changes

2020-04-23 16:30 UTC, vitalii-mak commented on client/src/styles/app.css
>  .btn-restaurants:hover{
![image](https://user-images.githubusercontent.com/6152066/80124250-a819ae80-8598-11ea-9aba-45d2865099c9.png)

Button is almost invisible over this background

2020-04-24 05:44 UTC, vitaliimak approved these changes
Cool! I can see text) 
But, you use very different styles on similar buttons, it isn't very good

There are github buttons
![image](https://user-images.githubusercontent.com/6152066/80178717-9cb19c00-8607-11ea-9e1d-407a3bd7d857.png)
![image](https://user-images.githubusercontent.com/6152066/80178738-a804c780-8607-11ea-86d6-11409d03865c.png)
![image](https://user-images.githubusercontent.com/6152066/80178758-b226c600-8607-11ea-810e-5b32b6cf43b6.png)
![image](https://user-images.githubusercontent.com/6152066/80178776-b94dd400-8607-11ea-8b19-3bf749a0f333.png)
A lot of pages, but button the same

2020-04-24 10:10 UTC, Melnyk9506 approved these changes
that ok

2020-04-24 11:53 UTC, VozNick approved these changes

2020-04-24 12:05 UTC, merged