Feature 133 fix token time limit
Social-projects-Rivne/Lunch_Time pull request #73
Opened 2020-04-23 13:55 UTC by Melnyk9506

guys max token time limit 24 days  for now

2020-04-23 16:35 UTC, vitalii-mak commented on server/src/main/java/com/lunchtime/security/JwtUtil.java
> +    private long timeLimit = miliseconds * seconds * minutes * hours * days;
Why you use both `long and int`?
Maybe it will be better to create privat method `getTimeLimit()`?

2020-04-24 05:47 UTC, vitaliimak requested changes
Don't fix a lot of issues in one PR

2020-04-24 05:47 UTC, vitalii-mak commented on client/src/services/person.js
> -          localStorage.setItem(this.userKey, response.data);
Why you remove this functionality in this PR? You should create new task for it

2020-04-24 15:27 UTC, vitaliimak approved these changes

2020-04-24 15:40 UTC, r-yevchuk approved these changes

2020-04-24 16:03 UTC, VozNick approved these changes

2020-04-24 16:03 UTC, merged